### ISSUE TITLE
The error of "No module named 'awsglue.transforms'" in lab 1

### ISSUE THREAD

**Issue by liualexiang** [aws-samples/amazon-cloudfront-log-analysis#2]
When you create [first glue ETL job in lab1](https://github.com/aws-samples/amazon-cloudfront-log-analysis/tree/master/lab1-serveless-cloudfront-log-analysis#create-aws-glue-etl-job), you may encounter an error as below:
```
Traceback (most recent call last):
File "/tmp/runscript.py", line 115, in <module>
runpy.run_path(temp_file_path, run_name='__main__')
File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/tmp/glue-python-scripts-7tb3qep1/tests.html", line 2, in <module>
ModuleNotFoundError: No module named 'awsglue.transforms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/runscript.py", line 134, in <module>
raise e_type(e_value).with_tracsback(new_stack)
AttributeError: 'ModuleNotFoundError' object has no attribute 'with_tracsback'
```
The reason is due to  ETL language is "Spark", but not "Python".

**Please modify the document, thanks**

**Comment by mmarionncern** [comment]
I fully support the observation, examples for using GLUE with python shell scripts are not correct, it would be good to get a proper and accurate example.
Thanks a lot

**Comment by jgdelrio** [comment]
I agree, the indications to add libraries are totally misleading and the error reported as 'ModuleNotFoundError' don't help to find where AWS was looking...
As it is clearly not looking at the location provided, go figure!

**Comment by BLAparna** [comment]
> When you create [first glue ETL job in lab1](https://github.com/aws-samples/amazon-cloudfront-log-analysis/tree/master/lab1-serveless-cloudfront-log-analysis#create-aws-glue-etl-job), you may encounter an error as below:
> 
> ```
> Traceback (most recent call last):
> File "/tmp/runscript.py", line 115, in <module>
> runpy.run_path(temp_file_path, run_name='__main__')
> File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/tmp/glue-python-scripts-7tb3qep1/tests.html", line 2, in <module>
> ModuleNotFoundError: No module named 'awsglue.transforms'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/tmp/runscript.py", line 134, in <module>
> raise e_type(e_value).with_tracsback(new_stack)
> AttributeError: 'ModuleNotFoundError' object has no attribute 'with_tracsback'
> ```
> 
> The reason is due to ETL language is "Spark", but not "Python".
> 
> **Please modify the document, thanks**

so how do i fix the error

**Comment by walter-sharethis** [comment]
This appears to be an AWS problem.   To reproduce:

1. From AWS console, open Glue page
2. From the left-hand navigation pane, click "Jobs"
3. At the top of the page is the "Create Job" box, with radio buttons for several different job types.
4. Select the "Python Shell script editor" radio button
5. Leave the default button "Create a new script with boilerplate code" selected rather than uploading your own code.
6. Now click the orange [Create] button in the upper-right.
7. You are now in the script editor window - give your job a name in the pane at the top.
8. NOTE: line 2 of the script code provided by AWS is `from awsglue.transforms import *`
9. Click the Job Details tab and enter a role for the job from the menu (perhaps the one you've used in the Add Crawlers tutorial).
10. You can also verify in this tab that it is a Python ETL job, according to AWS, using Python 3.6.
11. Click [Run] in the upper right corner of the page.
12. Now click the Runs tab (next to the Job Details tab).
13. You will see this job run, and run again, terminating with this error each time:
`ModuleNotFoundError: No module named 'awsglue.transforms'`
14. Let's try commenting out the line `from awsglue.transforms import *`
15. Now the script crashes with the error:
`ModuleNotFoundError: No module named 'pyspark'`

Perhaps these modules need to be provided by an explicit path, if there is a location given for them in the AWS Glue doc.
But if so, it's not obvious from the UI workflow.
